### ISSUE TITLE
Selected page tab is not highlighted upon navigation change

### ISSUE THREAD

**Issue by sowmenappd** [WinmezzZ/react-antd-admin#27]
Sidebar navigation clicks do not highlight actual tab for the new page currently selected. The page is however properly changed.

**Comment by sowmenappd** [comment]
@WinmezzZ please pull in my PR for fix #27

**Comment by WinmezzZ** [comment]
Thank you for your interest in this project.


The problem was not reproduced, it was fixed a few days ago, perhaps because your local code is not up to date?
`Online Preview Project`: [ https://react-admin.hyyar.com/documentation]( https://react-admin.hyyar.com/documentation)


If you look closely, you'll notice that the addTag method sets the activeTagID: [https://github.com/WinmezzZ/react-antd-admin/blob/master/src/stores/tags-view.store.ts#L19]( https://github.com/WinmezzZ/react-antd-admin/blob/master/src/stores/tags-view.store.ts#L19)

**Comment by WinmezzZ** [comment]
Thansk to your intrested this project and contribute!

A better way to fix this: [https://github.com/WinmezzZ/react-antd-admin/commit/25d524c23ce2464e98a8ca8d6e0730ef89874dea](https://github.com/WinmezzZ/react-antd-admin/commit/25d524c23ce2464e98a8ca8d6e0730ef89874dea)

 AddTag will be called each time menu was clicked, Duplicated menus are not added to the tags, but will update the value of activeTagId.

**Comment by sowmenappd** [comment]
Definitely better approach. Didn't have time to look into the store, would have don it myself, appreciate the reply back!

**Comment by sowmenappd** [comment]
> Thansk to your intrested this project and contribute!
> 
> A better way to fix this: [25d524c](https://github.com/WinmezzZ/react-antd-admin/commit/25d524c23ce2464e98a8ca8d6e0730ef89874dea)
> 
> AddTag will be called each time menu was clicked, Duplicated menus are not added to the tags, but will update the value of activeTagId.

Definitely better approach. Didn't have time to look into the store, would have don it myself, appreciate the reply back!
